import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'EN' | 'ZH';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    'Stay tuned': 'Stay tuned',
    // Topnav & Sidebar
    'VocInsight BI': 'VocInsight BI', // requested not to change
    'Data Access': 'Data Access',
    'VOC Insights': 'VOC Insights',
    'Self-service platform': 'Self-service platform',
    'My Models': 'My Models',
    'Insight Task': 'Insight Task',
    'Search': 'Search',
    'Reset': 'Reset',
    'Product Insight': 'Product Insight',
    'Core KPI Dashboard': 'Core KPI Dashboard',
    'Voice Closed-Loop': 'Voice Closed-Loop',
    'Public Sentiment Closed-Loop': 'Public Sentiment Closed-Loop',
    'Issue & Demand Closed-Loop': 'Issue & Demand Closed-Loop',

    // Core KPI Dashboard
    'Country / Brand / Series / Product/domain': 'Country / Brand / Series / Product/domain',
    'Star Rating': 'Star Rating',
    'Positive (4-5★)': 'Positive (4-5★)',
    'Negative (1-3★)': 'Negative (1-3★)',
    'Positive Rate': 'Positive Rate',
    'Negative Rate': 'Negative Rate',
    'United States': 'United States',
    'United Kingdom': 'United Kingdom',
    'Germany': 'Germany',
    'Italy': 'Italy',
    'Malaysia': 'Malaysia',

    // Tabbar
    'Single SKU Analysis': 'Single SKU Analysis',
    'Comparative Analysis': 'Comparative Analysis',
    'Self-service analytics': 'Self-service analytics',
    'Complete VocInsight user voice intelligence workspace for deep SKU sentiment profiles and operational alerts.': 'Complete VocInsight user voice intelligence workspace for deep SKU sentiment profiles and operational alerts.',
    'Compare competitive products to benchmark pain points, latent needs, experiences and usage scenarios.': 'Compare competitive products to benchmark pain points, latent needs, experiences and usage scenarios.',
    'Explore self-service multi-dimensional analytical workbenches and user segmentations.': 'Explore self-service multi-dimensional analytical workbenches and user segmentations.',
    'Monitor key performance indicators and sentiment trends across regions and brands.': 'Monitor key performance indicators and sentiment trends across regions and brands.',

    // Single SKU Header
    'Daily': 'Daily',
    'Weekly': 'Weekly',
    'Monthly': 'Monthly',
    'Yearly': 'Yearly',
    'Period': 'Period Summary',
    'Data Source': 'Data Source',
    'All Sources': 'All Sources',
    'E-commerce': 'E-commerce',
    'Social Media': 'Social Media',
    'Internal Data': 'Internal Data',
    'Category': 'Category',
    'All Categories': 'All Categories',
    'TV': 'TV',
    'Soundbar': 'Soundbars',
    'Home Theater': 'Home Theaters',
    'E-commerce Source': 'E-commerce Source',
    'All E-Commerce': 'All E-Commerce',
    'Walmart': 'Walmart',
    'Best Buy': 'Best Buy',
    'Amazon US': 'Amazon US',
    'JD.com (CN)': 'JD.com (CN)',
    'Amazon': 'Amazon',
    'Costco': 'Costco',
    'Brand': 'Brand',
    'All Brands': 'All Brands',
    'Hisense': 'Hisense',
    'Samsung': 'Samsung',
    'Sony': 'Sony',
    'TCL': 'TCL',
    'Product Country': 'Product Country',
    'All Countries': 'All Countries',
    'US': 'US',
    'CN': 'CN',
    'DE': 'DE',
    'Product Series': 'Product Series',
    'All Series': 'All Series',
    'U7K': 'U7K',
    'U8K': 'U8K',
    'U8K Series': 'U8K Series',
    'Product Name': 'Product Name',
    'e.g. 100U7K-US': 'e.g. 100U7K-US',
    'Product Platform': 'Product Platform',
    'All Platforms': 'All Platforms',
    'Is Vertical Review': 'Is Vertical Review',
    'All Ratings': 'All Ratings',
    'True': 'True',
    'False': 'False',
    'All Star Ratings': 'All',
    '5 Star reviews': '5 Star reviews',
    '4 Star reviews': '4 Star reviews',
    '3 Star reviews': '3 Star reviews',
    '2 Star reviews': '2 Star reviews',
    '1 Star reviews': '1 Star reviews',
    'Show Duplicate Review': 'Show Duplicate Review',
    'Yes': 'Yes',
    'No': 'No',
    'Size': 'Size',
    'All Sizes': 'All Sizes',
    '100': '100',
    '85': '85',
    '75': '75',
    'Keyword Query': 'Keyword Query',
    'Search keywords...': 'Search keywords...',
    'Selected SKU': 'Selected SKU',
    'Key Metrics': 'Key Metrics',
    'Issue Types': 'Issue Types',
    'Potential Requirements': 'Potential Requirements',
    'User Priorities': 'User Priorities',
    'Usage Scenarios': 'Usage Scenarios',
    'User Profile Analysis': 'User Profile Analysis',

    // Metric Cards
    'Total Voices': 'Total Voices',
    'Calculated from raw data stream': 'Calculated from raw data stream',
    'Platform Mentions': 'Platform Mentions',
    'Sentiment Score': 'Sentiment Score',
    'Negative Impact Rate': 'Negative Impact Rate',
    '+1.2% this week': '+1.2% this week',

    // Product Core Experience Issues
    'Product core experience issues': 'Product core experience issues',
    'Rank': 'Rank',
    'Level 2 Category': 'Level 2 Category',
    'Level 3 Category': 'Level 3 Category',
    'Level 4 Concern': 'Level 4 Concern',
    'Total Issues': 'Total Issues',
    'Proportion (%)': 'Proportion (%)',
    'YoY Trend': 'YoY Trend',
    'View Mentions': 'View Mentions',

    // Detailed User Voices
    'Detailed User Voices': 'Detailed User Voices',
    'Export Data': 'Export Data',

    // Top 100 Potential Requirements
    'Top 100 Potential Requirements': 'Top 100 Potential Requirements',
    'Requirement Target': 'Requirement Target',
    'Scenario Scope': 'Scenario Scope',
    'Requirement Description': 'Requirement Description',
    'Feasibility': 'Feasibility',
    'Volume': 'Volume',
    'Heat Score': 'Heat Score',

    // Multi-dimensional Concern
    'Multi-dimensional concern distribution': 'Multi-dimensional concern distribution',
    'View the hierarchical distribution of user concerns': 'View the hierarchical distribution of user concerns',
    
    // User Usage Scenario
    'User Usage Scenario': 'User Usage Scenario',
    'Understand implicit usage behaviors': 'Understand implicit usage behaviors',
    'Usage Scenario': 'Usage Scenario',
    'Volume Count': 'Volume Count',
    'Growth (YoY)': 'Growth (YoY)',
    'Placement Location': 'Placement Location',
    'Location Name': 'Location Name',
    'Location Mentions': 'Location Mentions',
    'External Device Name': 'External Device Name',
    'Device Target': 'Device Target',
    'Device Mentions': 'Device Mentions',

    // Comparative
    'Benchmark Competitors': 'Benchmark Competitors',
    'Primary Model': 'Primary Model',
    'Competitors (Max 3)': 'Competitors (Max 3)',
    'Price Segment Benchmark': 'Price Segment Benchmark',
    'User Rating': 'User Rating',
    'Price Sensitivity': 'Price Sensitivity',
    'Market Sentiment': 'Market Sentiment',
    'Brand Trust': 'Brand Trust',
    'Product Quality': 'Product Quality',
    'Feature Richness': 'Feature Richness',
    'Pain Scenarios by Model': 'Pain Scenarios by Model',
    'Identify competitor weakness and feature gaps': 'Identify competitor weakness and feature gaps',
    'Major Complaints': 'Major Complaints',
    'Signal Strength': 'Signal Strength',
    'Latent Needs Breakdown': 'Latent Needs Breakdown',
    'Uncovered user expectations mapped by brand': 'Uncovered user expectations mapped by brand',
    'Anticipated Need': 'Anticipated Need',
    'User Velocity': 'User Velocity',
    'Experience Pillars radar': 'Experience Pillars radar',
    'Aggregated sentiment scores across core pillars': 'Aggregated sentiment scores across core pillars',
    'Differentiated Usage Scenarios': 'Differentiated Usage Scenarios',
    'Where and how the competitors are being utilized': 'Where and how the competitors are being utilized',

    // Self Service
    'Sentiment Distribution': 'Sentiment Distribution',
    'Positive': 'Positive',
    'Negative': 'Negative',
    'Neutral': 'Neutral',
    'Total Mentions': 'Total Mentions',
    'E-commerce Mentions': 'E-commerce Mentions',
    'Social Media Mentions': 'Social Media Mentions',
    'Internal Data Mentions': 'Internal Data Mentions',
    'Data Statistics': 'Data Statistics',
    'Total User Voices': 'Total User Voices',
    'Valid Rate': 'Valid Rate',
    'Brands': 'Brands',
    'Expand': 'Expand',
    'Collapse': 'Collapse',
    'AI Analysis': 'AI Analysis',
    'Total Valid User Voices': 'Total Valid User Voices',
    'Positive highlights': 'Positive highlights',
    'Negative issues': 'Negative issues',
    'Neutral feedback': 'Neutral feedback',
    'Total voice summary': 'Total voice summary',

    // Misc
    'Total': 'Total',
  },
  ZH: {
    'Stay tuned': '敬请期待',
    // Topnav & Sidebar
    'VocInsight BI': 'VocInsight BI', // requested not to change
    'Data Access': '数据接入',
    'VOC Insights': 'VOC 洞察',
    'Self-service platform': '自助服务平台',
    'My Models': '我的模型',
    'Insight Task': '洞察任务',
    'Search': '搜索',
    'Reset': '重置',
    'Product Insight': '产品洞察',
    'Core KPI Dashboard': '核心 KPI 面板',
    'Voice Closed-Loop': '声音闭环',
    'Public Sentiment Closed-Loop': '舆情闭环',
    'Issue & Demand Closed-Loop': '问题与需求闭环',

    // Core KPI Dashboard
    'Country / Brand / Series / Product/domain': '国家 / 品牌 / 系列 / 产品/domain',
    'Star Rating': '星级评分',
    'Positive (4-5★)': '正面 (4-5★)',
    'Negative (1-3★)': '负面 (1-3★)',
    'Positive Rate': '好评率',
    'Negative Rate': '差评率',
    'United States': '美国',
    'United Kingdom': '英国',
    'Germany': '德国',
    'Italy': '意大利',
    'Malaysia': '马来西亚',

    // Tabbar
    'Single SKU Analysis': '单品分析',
    'Comparative Analysis': '竞品分析',
    'Self-service analytics': '自助分析',
    'Complete VocInsight user voice intelligence workspace for deep SKU sentiment profiles and operational alerts.': '完整的 VocInsight 用户声音智能工作区，用于深入的 SKU 情感画像和运营告警。',
    'Compare competitive products to benchmark pain points, latent needs, experiences and usage scenarios.': '比较竞品以标杆分析痛点、潜在需求、体验和使用场景。',
    'Explore self-service multi-dimensional analytical workbenches and user segmentations.': '探索自助式多维度分析工作台和用户分层。',
    'Monitor key performance indicators and sentiment trends across regions and brands.': '监控不同地区和品牌的关键绩效指标和情感趋势。',

    // Single SKU Header
    'Daily': '每日',
    'Weekly': '每周',
    'Monthly': '每月',
    'Yearly': '每年',
    'Period': '周期汇总',
    'Data Source': '数据源',
    'All Sources': '全部来源',
    'E-commerce': '电商',
    'Social Media': '社交媒体',
    'Internal Data': '内部数据',
    'Category': '品类',
    'All Categories': '全部分类',
    'TV': '电视',
    'Soundbar': '音响/条形音箱',
    'Home Theater': '家庭影院',
    'E-commerce Source': '电商来源',
    'All E-Commerce': '全部电商',
    'Walmart': '沃尔玛',
    'Best Buy': '百思买',
    'Amazon US': '亚马逊美国',
    'JD.com (CN)': '京东商城',
    'Amazon': '亚马逊',
    'Costco': '开市客',
    'Brand': '品牌',
    'All Brands': '全部品牌',
    'Hisense': '海信',
    'Samsung': '三星',
    'Sony': '索尼',
    'TCL': 'TCL',
    'Product Country': '产品国家',
    'All Countries': '全部国家',
    'US': '美国',
    'CN': '中国',
    'DE': '德国',
    'Product Series': '产品系列',
    'All Series': '全部分类',
    'U7K': 'U7K',
    'U8K': 'U8K',
    'U8K Series': 'U8K 系列',
    'Product Name': '产品名称',
    'e.g. 100U7K-US': '例如：100U7K-US',
    'Product Platform': '产品平台',
    'All Platforms': '全部平台',
    'Is Vertical Review': '是否垂直评论',
    'All Ratings': '所有评价',
    'True': '是',
    'False': '否',
    'All Star Ratings': '全部',
    '5 Star reviews': '5星评价',
    '4 Star reviews': '4星评价',
    '3 Star reviews': '3星评价',
    '2 Star reviews': '2星评价',
    '1 Star reviews': '1星评价',
    'Show Duplicate Review': '显示重复评价',
    'Yes': '是',
    'No': '否',
    'Size': '尺寸',
    'All Sizes': '全部尺寸',
    '100': '100',
    '85': '85',
    '75': '75',
    'Keyword Query': '关键词查询',
    'Search keywords...': '搜索关键词...',
    'Selected SKU': '已选 SKU',
    'Key Metrics': '核心指标',
    'Issue Types': '问题类型',
    'Potential Requirements': '潜在需求',
    'User Priorities': '用户层级诉求',
    'Usage Scenarios': '使用场景',
    'User Profile Analysis': '用户画像分析',

    // Metric Cards
    'Total Voices': '总声量',
    'Calculated from raw data stream': '基于原始数据流计算',
    'Platform Mentions': '平台提及量',
    'Sentiment Score': '情感得分',
    'Negative Impact Rate': '负面影响率',
    '+1.2% this week': '本周 +1.2%',

    // Product Core Experience Issues
    'Product core experience issues': '产品核心体验问题',
    'Rank': '排名',
    'Level 2 Category': '二级分类',
    'Level 3 Category': '三级分类',
    'Level 4 Concern': '四级关注点',
    'Total Issues': '总问题数',
    'Proportion (%)': '占比 (%)',
    'YoY Trend': '同比趋势',
    'View Mentions': '查看提及详情',

    // Detailed User Voices
    'Detailed User Voices': '用户原声详情',
    'Export Data': '导出数据',

    // Top 100 Potential Requirements
    'Top 100 Potential Requirements': 'TOP 100 潜在需求储备',
    'Requirement Target': '需求目标',
    'Scenario Scope': '场景范围',
    'Requirement Description': '需求描述',
    'Feasibility': '可行性',
    'Volume': '声量',
    'Heat Score': '热度得分',

    // Multi-dimensional Concern
    'Multi-dimensional concern distribution': '多维关注点分布',
    'View the hierarchical distribution of user concerns': '查看用户关注点的层级分布',
    
    // User Usage Scenario
    'User Usage Scenario': '用户使用场景',
    'Understand implicit usage behaviors': '深入了解隐性使用行为',
    'Usage Scenario': '使用场景',
    'Volume Count': '声量计数',
    'Growth (YoY)': '增速 (YoY)',
    'Placement Location': '摆放位置',
    'Location Name': '位置名称',
    'Location Mentions': '位置提及数',
    'External Device Name': '外接设备名称',
    'Device Target': '设备目标',
    'Device Mentions': '设备提及数',

    // Comparative
    'Benchmark Competitors': '对比竞品',
    'Primary Model': '基准模型',
    'Competitors (Max 3)': '对标竞品 (最多3个)',
    'Price Segment Benchmark': '价格段基准',
    'User Rating': '用户评分',
    'Price Sensitivity': '价格敏感度',
    'Market Sentiment': '市场情感',
    'Brand Trust': '品牌信任度',
    'Product Quality': '产品质量',
    'Feature Richness': '功能丰富度',
    'Pain Scenarios by Model': '竞品痛点场景',
    'Identify competitor weakness and feature gaps': '识别竞品劣势和功能差距',
    'Major Complaints': '主要投诉点',
    'Signal Strength': '信号强度',
    'Latent Needs Breakdown': '潜在需求明细',
    'Uncovered user expectations mapped by brand': '各品牌未满足的用户期望',
    'Anticipated Need': '预期需求',
    'User Velocity': '用户增速',
    'Experience Pillars radar': '体验支柱雷达图',
    'Aggregated sentiment scores across core pillars': '核心支柱的综合情感得分',
    'Differentiated Usage Scenarios': '差异化使用场景',
    'Where and how the competitors are being utilized': '竞品的使用场景与方式',

    // Self Service
    'Sentiment Distribution': '情感分布',
    'Positive': '正面',
    'Negative': '负面',
    'Neutral': '中性',
    'Total Mentions': '总提及数',
    'E-commerce Mentions': '电商提及数',
    'Social Media Mentions': '社媒提及数',
    'Internal Data Mentions': '内部数据提及数',
    'Data Statistics': '数据统计',
    'Total User Voices': '总用户原声',
    'Valid Rate': '有效率',
    'Brands': '涵盖品牌',
    'Expand': '展开查看',
    'Collapse': '收起',
    'AI Analysis': 'AI 深度分析',
    'Total Valid User Voices': '总有效用户原声',
    'Positive highlights': '正面褒奖提炼',
    'Negative issues': '负面问题汇总',
    'Neutral feedback': '中性反馈概览',
    'Total voice summary': '整体声量总结',

    // Misc
    'Total': '全部',
  }
};

export const LanguageContext = createContext<LanguageContextType>({
  language: 'EN',
  toggleLanguage: () => {},
  t: (k: string) => k,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('EN');

  const toggleLanguage = () => setLanguage((prev) => (prev === 'EN' ? 'ZH' : 'EN'));

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
